name: Jazz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  responsive_framework: ^1.5.1
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.2
  google_maps_flutter: ^2.9.0
  geolocator: any
  latlng: ^2.0.7
  flutter_map: ^7.0.2
  firebase_storage: ^12.3.0
  cloud_firestore: ^5.4.1
  shared_preferences: ^2.3.2
  firebase_core: ^3.4.1
  firebase_database: ^11.1.2
  fluttertoast: ^8.2.8
  geocoding: ^3.0.0
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  location: any
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  http: ^1.2.2
  pinput: ^5.0.0
  flutter_svg: ^2.0.10+1
  icons_launcher: ^3.0.0
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/jazz.png
icons_launcher:
  image_path: "assets/images/jazz ap icon logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
flutter:
  uses-material-design: true

  assets:
    - assets/images/
